version: '3'

services:
  postgres:
    image: postgres:9.5
    restart: always
    container_name: serverGcar
    environment:
      POSTGRES_USER: "gcar"      
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "gcar"
    ports:
        - "5432:5432"
    volumes:
      - gcar_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080

  gcar-app:
    build:                # Instrucciones para crear imagen
      context: .          # Dontexto actual
      dockerfile: ./Dockerfile # Nombre Dockerfile
    restart: always
    image: suvin1/gcar_app
    container_name: gcar_app
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - default
volumes:
  gcar_data:
                    #    enviroments:
                    #      VIRTUAL_HOST: LOCALHOST